name       : zig
version    : 0.9.1
release    : 3
source     :
    - https://github.com/ziglang/zig/archive/refs/tags/0.9.1.tar.gz : 2a6ba6a72b9619b83dab77f5b6e2b6f0958bb0f85cded055be2c632386e0ff2d
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/llvm-project-13.0.1.src.tar.xz : 326335a830f2e32d06d0a36393b5455d17dc73e0bd1211065227ee014f92cbf8
license    : MIT
component  : programming
summary    : General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
description: |
    General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software. 
clang      : yes
builddeps  :
    - llvm-clang-devel
setup      : |
    # Build bundled LLVM
    mkdir llvm-src llvm-bundled
    tar xf $sources/llvm-project-13.0.1.src.tar.xz -C $workdir/llvm-src --strip=1
    pushd llvm-src/llvm
        cmake -G Ninja -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=$workdir/llvm-bundled \
        -DENABLE_PROJECTS="llvm;clang;lld" \
        -DLLVM_ENABLE_LIBXML2=OFF \
        -DLLVM_ENABLE_TERMINFO=OFF \
        -DLLVM_ENABLE_RTTI=ON # system lld has rtti grrr
        ninja -C build install -v
    popd

    %cmake \
        -DZIG_PREFER_CLANG_CPP_DYLIB=OFF \
        -DZIG_STATIC_LLVM=ON \
        -DCMAKE_PREFIX_PATH=$workdir/llvm-bundled
build      : |
    %make -d
install    : |
    %make_install -d
check      : |
    pushd `mktemp -d`
        $workdir/zig init-exe
        $workdir/zig build run
        $workdir/zig build test
    popd

