name       : zig
version    : 0.11.0
release    : 7
source     :
    - https://github.com/ziglang/zig/archive/refs/tags/0.11.0.tar.gz : 71de3e958293dffaa17f7ad1438c775389f5406991c96b533bb1501178092b02
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-project-16.0.6.src.tar.xz : ce5e71081d17ce9e86d7cbcfa28c4b04b9300f8fb7e78422b1feb6bc52c3028e
license    : MIT
component  : programming
summary    : General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
description: |
    General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
clang      : yes
builddeps  :
    - git
    - llvm-clang-devel
setup      : |
    # https://dev.getsol.us/T10610#203178
    mkdir llvm-src llvm-bundled llvm-src/build
    tar xf $sources/llvm-project-16.0.6.src.tar.xz -C $workdir/llvm-src --strip=1
    pushd llvm-src/build
        cmake ../llvm \
        -DCMAKE_INSTALL_PREFIX=$workdir/llvm-bundled \
        -DCMAKE_BUILD_TYPE=Release \
        -DLLVM_ENABLE_PROJECTS="lld;clang" \
        -DLLVM_ENABLE_LIBXML2=OFF \
        -DLLVM_ENABLE_TERMINFO=OFF \
        -DLLVM_ENABLE_LIBEDIT=OFF \
        -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_PARALLEL_LINK_JOBS=1 \
        -G Ninja
        ninja install -v
    popd
    # https://github.com/ziglang/zig/issues/14393
    %cmake \
        -DZIG_PREFER_CLANG_CPP_DYLIB=OFF \
        -DZIG_STATIC_LLVM=ON \
        -DCMAKE_PREFIX_PATH=$workdir/llvm-bundled \
        -DZIG_TARGET_MCPU=baseline
build      : |
    %make -d
install    : |
    %make_install -d
check      : |
    pushd `mktemp -d`
        $installdir/usr/bin/zig init-exe
        $installdir/usr/bin/zig build run
        $installdir/usr/bin/zig build test
    popd
