name       : zig
version    : 0.9.0
release    : 1
source     :
    - https://github.com/ziglang/zig/archive/refs/tags/0.9.0.tar.gz : 5a01d7ae22b1bee1292a8688e8847c07bb31279d1a496808675002237ad0f7e5
license    : MIT
component  : programming
summary    : General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software. 
description: |
    General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software. 
clang : yes
builddeps  :
    - llvm-clang-devel
setup      : |
    %cmake -DZIG_PREFER_CLANG_CPP_DYLIB=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    pushd `mktemp -d`
        $workdir/zig init-exe
        $workdir/zig build run
        $workdir/zig build test
    popd

