name       : zig
version    : 0.10.1
release    : 5
source     :
    - https://github.com/ziglang/zig/archive/refs/tags/0.10.1.tar.gz : b511709d5276eca9bd706924d7928c7477fe799ad62d5d37f5f90d7dceadfa2a
license    : MIT
component  : programming
summary    : General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
description: |
    General-purpose programming language and toolchain for maintaining robust, optimal, and reusable software.
clang      : yes
builddeps  :
    - git
    - llvm-clang-devel
setup      : |
    mkdir $workdir/build
build      : |
    # https://github.com/ziglang/zig/issues/14393
    cd $workdir/build
    cmake $workdir -DZIG_TARGET_MCPU=baseline
install    : |
    cd $workdir/build
    %make_install
    mv -f $installdir/home/build/YPKG/root/zig/build/zig-0.10.1/build/stage3 $installdir/usr
    rm -rf $installdir/home
check      : |
    pushd `mktemp -d`
        $installdir/usr/bin/zig init-exe
        $installdir/usr/bin/zig build run
        $installdir/usr/bin/zig build test
    popd
